name: deployment workflow
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install contract dependencies
        run: npm ci

      - name: Test contract
        run: npx hardhat test

      - name: Install client dependencies
        run: cd client && npm ci

      - name: Build client
        run: cd client && npm run build
